import 'package:flutter/material.dart';
import 'package:loqma/features/swap/data/swap_repository.dart';

class SwapListingsPage extends StatefulWidget {
  const SwapListingsPage({super.key});
  @override State<SwapListingsPage> createState() => _SwapListingsPageState();
}
class _SwapListingsPageState extends State<SwapListingsPage> {
  final _repo = SwapRepository();
  final _search = TextEditingController();
  late Future<List<Map<String, dynamic>>> _future;
  @override void initState() { super.initState(); _future = _repo.listOpenListings(); }
  @override void dispose() { _search.dispose(); super.dispose(); }
  void _reload() => setState(() => _future = _repo.listOpenListings(search: _search.text));
  @override Widget build(BuildContext context) {
    final c = Theme.of(context).colorScheme;
    return Directionality(textDirection: TextDirection.rtl, child: Scaffold(
      appBar: AppBar(title: const Text('استبدال شيء'), actions: [IconButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const MySwapsPage())), icon: const Icon(Icons.swap_horizontal_circle_rounded))]),
      floatingActionButton: FloatingActionButton.extended(onPressed: () async { final ok = await Navigator.push(context, MaterialPageRoute(builder: (_) => const CreateSwapListingPage())); if (ok == true) _reload(); }, icon: const Icon(Icons.add_rounded), label: const Text('إضافة استبدال')),
      body: RefreshIndicator(onRefresh: () async => _reload(), child: FutureBuilder<List<Map<String, dynamic>>>(future: _future, builder: (context, snap) {
        if (snap.connectionState == ConnectionState.waiting) return Center(child: CircularProgressIndicator(color: c.primary));
        if (snap.hasError) return _StateMessage(title: 'تعذر تحميل الاستبدالات', onRetry: _reload);
        final rows = snap.data ?? const <Map<String, dynamic>>[];
        return ListView(padding: const EdgeInsets.fromLTRB(16, 12, 16, 100), children: [
          _IntroCard(color: c.primary), const SizedBox(height: 12),
          TextField(controller: _search, onSubmitted: (_) => _reload(), textInputAction: TextInputAction.search, decoration: const InputDecoration(prefixIcon: Icon(Icons.search_rounded), hintText: 'ابحث عن شيء مطلوب...')),
          const SizedBox(height: 16),
          if (rows.isEmpty) const _StateMessage(title: 'لا توجد استبدالات منشورة حاليًا') else ...rows.map((r) => _ListingCard(row: r, onTap: () async { await Navigator.push(context, MaterialPageRoute(builder: (_) => SwapDetailsPage(listingId: r['id'].toString()))); if (mounted) _reload(); })),
        ]);
      })),
    ));
  }
}

class CreateSwapListingPage extends StatefulWidget { const CreateSwapListingPage({super.key}); @override State<CreateSwapListingPage> createState() => _CreateSwapListingPageState(); }
class _CreateSwapListingPageState extends State<CreateSwapListingPage> {
  final _form = GlobalKey<FormState>(); final _title = TextEditingController(); final _desc = TextEditingController(); final _category = TextEditingController(); final _repo = SwapRepository(); String _condition = 'any'; bool _busy = false;
  @override void dispose() { _title.dispose(); _desc.dispose(); _category.dispose(); super.dispose(); }
  Future<void> _save() async { if (!_form.currentState!.validate()) return; setState(() => _busy = true); try { await _repo.createListing(wantedTitle: _title.text, description: _desc.text, category: _category.text, wantedCondition: _condition); if (mounted) Navigator.pop(context, true); } catch (e) { if (mounted) _toast(context, e.toString()); } finally { if (mounted) setState(() => _busy = false); } }
  @override Widget build(BuildContext context) { final c = Theme.of(context).colorScheme; return Directionality(textDirection: TextDirection.rtl, child: Scaffold(appBar: AppBar(title: const Text('إضافة استبدال')), body: Form(key: _form, child: ListView(padding: const EdgeInsets.all(20), children: [const Text('اطلب الشيء الذي تريد الحصول عليه', style: TextStyle(fontSize: 22, fontWeight: FontWeight.w800)), const SizedBox(height: 8), const Text('مثال: أريد استبدال لابتوب قديم بآيفون 11. سيظهر إعلانك لكل المستخدمين.'), const SizedBox(height: 22), TextFormField(controller: _title, decoration: const InputDecoration(labelText: 'ما الشيء المطلوب؟', hintText: 'مثال: iPhone 11'), validator: (v) => v == null || v.trim().length < 3 ? 'اكتب الشيء المطلوب' : null), const SizedBox(height: 14), TextFormField(controller: _desc, minLines: 4, maxLines: 7, decoration: const InputDecoration(labelText: 'التفاصيل', hintText: 'اشرح ما الذي ستقدمه أو حالة الشيء الذي تريد استبداله...'), validator: (v) => v == null || v.trim().length < 10 ? 'اكتب تفاصيل أكثر' : null), const SizedBox(height: 14), TextFormField(controller: _category, decoration: const InputDecoration(labelText: 'التصنيف', hintText: 'إلكترونيات، ملابس، أثاث...')), const SizedBox(height: 14), DropdownButtonFormField<String>(value: _condition, decoration: const InputDecoration(labelText: 'الحالة المطلوبة'), items: const [DropdownMenuItem(value: 'any', child: Text('أي حالة')), DropdownMenuItem(value: 'new', child: Text('جديد')), DropdownMenuItem(value: 'like_new', child: Text('شبه جديد')), DropdownMenuItem(value: 'good', child: Text('جيد')), DropdownMenuItem(value: 'used', child: Text('مستعمل'))], onChanged: (v) => setState(() => _condition = v ?? 'any')), const SizedBox(height: 28), FilledButton.icon(onPressed: _busy ? null : _save, icon: _busy ? const SizedBox(width: 18, height: 18, child: CircularProgressIndicator(strokeWidth: 2)) : const Icon(Icons.publish_rounded), label: const Text('نشر الاستبدال'), style: FilledButton.styleFrom(backgroundColor: c.primary))]))); }
}

class SwapDetailsPage extends StatefulWidget { final String listingId; const SwapDetailsPage({super.key, required this.listingId}); @override State<SwapDetailsPage> createState() => _SwapDetailsPageState(); }
class _SwapDetailsPageState extends State<SwapDetailsPage> { final _repo = SwapRepository(); late Future<Map<String, dynamic>> _future; @override void initState() { super.initState(); _future = _repo.getListing(widget.listingId); } void _reload() => setState(() => _future = _repo.getListing(widget.listingId));
  Future<void> _addProposal() async { final ok = await showModalBottomSheet<bool>(context: context, isScrollControlled: true, builder: (_) => _ProposalSheet(listingId: widget.listingId, repo: _repo)); if (ok == true) _reload(); }
  @override Widget build(BuildContext context) { final c = Theme.of(context).colorScheme; return Directionality(textDirection: TextDirection.rtl, child: Scaffold(appBar: AppBar(title: const Text('تفاصيل الاستبدال')), body: FutureBuilder<Map<String, dynamic>>(future: _future, builder: (context, snap) { if (!snap.hasData) return Center(child: snap.hasError ? const Text('تعذر تحميل التفاصيل') : CircularProgressIndicator(color: c.primary)); final r = snap.data!; final proposals = (r['proposals'] as List? ?? []).cast<Map<String, dynamic>>(); final owner = r['owner_id']?.toString() == _repoUserId(); return ListView(padding: const EdgeInsets.all(20), children: [Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('أريد استبدال:', style: TextStyle(color: c.primary, fontWeight: FontWeight.w800)), const SizedBox(height: 6), Text(r['wanted_title']?.toString() ?? '', style: const TextStyle(fontSize: 24, fontWeight: FontWeight.w900)), const SizedBox(height: 14), Text(r['description']?.toString() ?? ''), const SizedBox(height: 12), Wrap(spacing: 8, children: [Chip(label: Text(r['category']?.toString() ?? 'أخرى')), Chip(label: Text(_conditionLabel(r['wanted_condition']?.toString())))])])), const SizedBox(height: 18), if (!owner && r['status'] == 'open') FilledButton.icon(onPressed: _addProposal, icon: const Icon(Icons.add_business_rounded), label: const Text('إضافة شيء مقابل')), const SizedBox(height: 18), Text('العروض المقترحة (${proposals.length})', style: const TextStyle(fontSize: 19, fontWeight: FontWeight.w900)), const SizedBox(height: 8), if (proposals.isEmpty) const _StateMessage(title: 'لم يضف أحد عرضًا مقابلًا بعد') else ...proposals.map((p) => _ProposalCard(proposal: p, isOwner: owner, repo: _repo, onChanged: _reload))]); }))); }
  String? _repoUserId() => _repo.currentUserId;
}

class _ProposalSheet extends StatefulWidget { final String listingId; final SwapRepository repo; const _ProposalSheet({required this.listingId, required this.repo}); @override State<_ProposalSheet> createState() => _ProposalSheetState(); }
class _ProposalSheetState extends State<_ProposalSheet> { final _form = GlobalKey<FormState>(); final _title = TextEditingController(); final _desc = TextEditingController(); String _condition = 'good'; bool _busy = false; @override void dispose() { _title.dispose(); _desc.dispose(); super.dispose(); } Future<void> _send() async { if (!_form.currentState!.validate()) return; setState(() => _busy = true); try { await widget.repo.createProposal(listingId: widget.listingId, offeredTitle: _title.text, offeredDescription: _desc.text, offeredCondition: _condition); if (mounted) Navigator.pop(context, true); } catch (e) { if (mounted) _toast(context, e.toString()); } finally { if (mounted) setState(() => _busy = false); } } @override Widget build(BuildContext context) { return Padding(padding: EdgeInsets.fromLTRB(20, 20, 20, MediaQuery.viewInsetsOf(context).bottom + 20), child: Form(key: _form, child: Column(mainAxisSize: MainAxisSize.min, children: [Text('ماذا ستقدم في المقابل؟', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 14), TextFormField(controller: _title, decoration: const InputDecoration(labelText: 'اسم الشيء'), validator: (v) => v == null || v.trim().length < 3 ? 'مطلوب' : null), const SizedBox(height: 10), TextFormField(controller: _desc, minLines: 3, maxLines: 5, decoration: const InputDecoration(labelText: 'تفاصيل الشيء وحالته'), validator: (v) => v == null || v.trim().length < 10 ? 'اكتب تفاصيل أكثر' : null), const SizedBox(height: 10), DropdownButtonFormField(value: _condition, items: const [DropdownMenuItem(value: 'new', child: Text('جديد')), DropdownMenuItem(value: 'like_new', child: Text('شبه جديد')), DropdownMenuItem(value: 'good', child: Text('جيد')), DropdownMenuItem(value: 'used', child: Text('مستعمل')), DropdownMenuItem(value: 'needs_repair', child: Text('يحتاج إصلاح'))], onChanged: (v) => setState(() => _condition = v ?? 'good')), const SizedBox(height: 16), SizedBox(width: double.infinity, child: FilledButton(onPressed: _busy ? null : _send, child: Text(_busy ? 'جارٍ الإرسال...' : 'إرسال العرض')))])); } }

class MySwapsPage extends StatefulWidget { const MySwapsPage({super.key}); @override State<MySwapsPage> createState() => _MySwapsPageState(); }
class _MySwapsPageState extends State<MySwapsPage> with SingleTickerProviderStateMixin { final _repo = SwapRepository(); late TabController _tabs; late Future<List<Map<String, dynamic>>> _proposals; late Future<List<Map<String, dynamic>>> _listings; @override void initState() { super.initState(); _tabs = TabController(length: 2, vsync: this); _load(); } void _load() { _proposals = _repo.myProposals(); _listings = _repo.myListings(); if (mounted) setState(() {}); } @override void dispose() { _tabs.dispose(); super.dispose(); } @override Widget build(BuildContext context) { final c = Theme.of(context).colorScheme; return Directionality(textDirection: TextDirection.rtl, child: Scaffold(appBar: AppBar(title: const Text('استبدالاتي'), bottom: TabBar(controller: _tabs, tabs: const [Tab(text: 'عروضي'), Tab(text: 'إعلاناتي')], onTap: (_) => setState(() {}))), body: TabBarView(controller: _tabs, children: [_ProposalList(future: _proposals, repo: _repo, reload: _load), _ListingList(future: _listings, repo: _repo, reload: _load)]))); } }
class _ProposalList extends StatelessWidget { final Future<List<Map<String, dynamic>>> future; final SwapRepository repo; final VoidCallback reload; const _ProposalList({required this.future, required this.repo, required this.reload}); @override Widget build(BuildContext context) => FutureBuilder<List<Map<String, dynamic>>>(future: future, builder: (context, s) => _asyncList(s, (r) => Card(child: ListTile(leading: const Icon(Icons.call_made_rounded), title: Text(r['offered_title']?.toString() ?? ''), subtitle: Text('على: ${(r['swap_listings'] as Map?)?['wanted_title'] ?? ''}\nالحالة: ${_statusLabel(r['status'])}'), isThreeLine: true, trailing: r['status'] == 'pending' ? IconButton(onPressed: () async { await repo.updateProposalStatus(proposalId: r['id'].toString(), status: 'withdrawn'); reload(); }, icon: const Icon(Icons.undo_rounded)) : null))); }
class _ListingList extends StatelessWidget { final Future<List<Map<String, dynamic>>> future; final SwapRepository repo; final VoidCallback reload; const _ListingList({required this.future, required this.repo, required this.reload}); @override Widget build(BuildContext context) => FutureBuilder<List<Map<String, dynamic>>>(future: future, builder: (context, s) => _asyncList(s, (r) { final ps = (r['swap_proposals'] as List? ?? []).cast<Map<String, dynamic>>(); return Card(child: ListTile(title: Text(r['wanted_title']?.toString() ?? ''), subtitle: Text('${ps.length} عرض مقابل\nالحالة: ${_statusLabel(r['status'])}'), trailing: IconButton(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => SwapDetailsPage(listingId: r['id'].toString()))), icon: const Icon(Icons.arrow_forward_ios_rounded, size: 18)) ); })); }
Widget _asyncList<T>(AsyncSnapshot<List<Map<String, dynamic>>> s, Widget Function(Map<String, dynamic>) item) { if (s.connectionState == ConnectionState.waiting) return const Center(child: CircularProgressIndicator()); if (s.hasError) return const _StateMessage(title: 'تعذر تحميل البيانات'); final rows = s.data ?? []; return rows.isEmpty ? const _StateMessage(title: 'لا توجد استبدالات هنا') : ListView(padding: const EdgeInsets.all(16), children: rows.map(item).toList()); }

class _ProposalCard extends StatelessWidget { final Map<String, dynamic> proposal; final bool isOwner; final SwapRepository repo; final VoidCallback onChanged; const _ProposalCard({required this.proposal, required this.isOwner, required this.repo, required this.onChanged}); @override Widget build(BuildContext context) { final c = Theme.of(context).colorScheme; final user = proposal['users'] as Map?; return Card(child: Padding(padding: const EdgeInsets.all(14), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(proposal['offered_title']?.toString() ?? '', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w800)), Text(proposal['offered_description']?.toString() ?? ''), const SizedBox(height: 6), Text('من: ${user?['name'] ?? 'مستخدم'} • ${_statusLabel(proposal['status'])}', style: TextStyle(color: c.onSurfaceVariant)), if (isOwner && proposal['status'] == 'pending') Row(mainAxisAlignment: MainAxisAlignment.end, children: [TextButton(onPressed: () async { await repo.updateProposalStatus(proposalId: proposal['id'].toString(), status: 'rejected'); onChanged(); }, child: const Text('رفض')), FilledButton(onPressed: () async { await repo.updateProposalStatus(proposalId: proposal['id'].toString(), status: 'accepted'); onChanged(); }, child: const Text('قبول'))])]))); } }
class _ListingCard extends StatelessWidget { final Map<String, dynamic> row; final VoidCallback onTap; const _ListingCard({required this.row, required this.onTap}); @override Widget build(BuildContext context) { final c = Theme.of(context).colorScheme; final user = row['users'] as Map?; return Card(margin: const EdgeInsets.only(bottom: 12), child: InkWell(onTap: onTap, borderRadius: BorderRadius.circular(16), child: Padding(padding: const EdgeInsets.all(16), child: Row(children: [CircleAvatar(backgroundColor: c.primaryContainer, child: Icon(Icons.swap_horiz_rounded, color: c.onPrimaryContainer)), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('مطلوب: ${row['wanted_title']}', style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 17)), const SizedBox(height: 5), Text(row['description']?.toString() ?? '', maxLines: 2, overflow: TextOverflow.ellipsis), const SizedBox(height: 5), Text('${user?['name'] ?? 'مستخدم'} • ${row['category'] ?? 'أخرى'}', style: TextStyle(color: c.onSurfaceVariant, fontSize: 12))]))]))); } }
class _IntroCard extends StatelessWidget { final Color color; const _IntroCard({required this.color}); @override Widget build(BuildContext context) => Card(color: color, child: const Padding(padding: EdgeInsets.all(20), child: Row(children: [Icon(Icons.swap_horizontal_circle_rounded, color: Colors.white, size: 42), SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('استبدل بدل ما تشتري', style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.w900)), SizedBox(height: 5), Text('انشر ما تريد، واستقبل عروضًا من المجتمع.', style: TextStyle(color: Colors.white70))]))])); }
class _StateMessage extends StatelessWidget { final String title; final VoidCallback? onRetry; const _StateMessage({required this.title, this.onRetry}); @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.all(40), child: Column(children: [Icon(Icons.swap_horizontal_circle_outlined, size: 52, color: Theme.of(context).colorScheme.outline), const SizedBox(height: 12), Text(title, textAlign: TextAlign.center), if (onRetry != null) TextButton(onPressed: onRetry, child: const Text('إعادة المحاولة'))])); }
String _conditionLabel(String? v) => {'any': 'أي حالة', 'new': 'جديد', 'like_new': 'شبه جديد', 'good': 'جيد', 'used': 'مستعمل', 'needs_repair': 'يحتاج إصلاح'}[v] ?? 'غير محدد';
String _statusLabel(Object? v) => {'pending': 'في الانتظار', 'accepted': 'مقبول', 'rejected': 'مرفوض', 'withdrawn': 'مسحوب', 'open': 'مفتوح', 'closed': 'مغلق'}[v?.toString()] ?? 'غير معروف';
void _toast(BuildContext context, Object e) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString().replaceFirst('Exception: ', ''))));
